language: node_js
node_js:
  - node
cache: bundler
deploy:
  provider: heroku
  api_key:
    secure: hNUvchQfxmjQNVNX+fNSlEZ9HA/x4Ha2wYXOIEtxSrG+eHglrTZHWNsXJzqb1D+AfO99Eof9TJHAROxr3n/XLI3YI9NK4mYfbyV4MXX8pOqY5Ba4mghw4dFf8GxTNJrI2Ebfpf7r5M80CPtuLfuukF2Ol0qB2LxUQYlWeUK05+oO7BDjAPDJMix3Uoja5ot2Eznbq1dZfS8R9iWleaP1lLCE7tGfHeOpiPx82h6plHr/YvIgIktjCIqs1soA9uQams+q7q3z20yznfFWIe2gJEdot/BXdQZ+FmnMxCknfnNuxfloAq9IlAflNngyjiIQDWfxLG5aADRBaCOEsOwiyDz6aSO2W8MyayksXSXBKgvsUgY/U12PR6rYIn3Jkd77wysAzFTAZai0e3kh52pbPFrwhBPxrkwbGJkN03EWTOwbMJ+qwDQb343+srueNF2FwWUj8Z2gYeDY+KuP/lKvnwgeg3VLxJuyKMrJQCvmEZV4w4BkZBLvCEY5B7OMIo8CnY5GLm4f2IcO6HVN1aDeugl1slOmTvwuO8jgy46znPjaU5ASQ2znF/TkKP7JoHoA2ohxEjpaENR4QWAHyQz8d2eXCBAJrsgU8XvkfGODMjkNimmTLXcH15oIBOT5HDMo18dH9+QehYbu1SHn0Sdj85vJwAJh8K8XGg0u2tQ4v0c=
  app: nestjs-test